# Generated by Django 3.1.1 on 2022-02-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220214_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_sizes',
            field=models.CharField(blank=True, default=True, max_length=256, null=True),
        ),
    ]
