# Generated by Django 3.1.1 on 2022-02-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220215_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_sizes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
